\newpage

# Annexe `r new_appendix()`. Workshop agenda and list of participants {#app:first-appendix}

## Agenda

## List of participants
```{r}
my.df <- read.csv("./data/participants-EN.csv", encoding = "utf8")

ft_1 <- flextable::qflextable(
  my.df
  )
set_table_properties(ft_1, width = 1, layout = "autofit")

```

\newpage

# Annexe `r new_appendix()`. Abstracts for contributed and invited presentations, ordered according to the Agenda  {#app:second-appendix}

## Introduction to the EAFM Methods Toolbox (Hugues Benoît, QC)  
Fisheries and Oceans Canada’s (DFO) national Ecosystem Approach to Fisheries Management (EAFM) Working Group developed a National EAFM Science Methods Toolbox and published an associated user’s guide in 2025. The ‘toolbox’ is best viewed as an indexed searchable catalogue of methods and approaches for scientific support of EAFM. Methods are organized according to broad classes and users can search according to research objectives, management considerations and input data requirements, for instance, to identify candidate methods. Brief descriptions and key associated references for each methods are available in the Toolbox User’s Guide, which has been published as a DFO technical report. The ‘toolbox’ is not considered to constitute an exhaustive inventory of all available methods relevant to EAFM. Rather, it is expected to remain ‘evergreen’, with periodic updates to reflect emerging best practices. The present workshop is expected to contribute to that end. 

## An approach for providing stock advice under ecosystem impacts with data and model limitations (Meghan Burton, PAC)  

Many marine invertebrate stocks are not managed using traditional stock assessment models which makes it more difficult to include ecosystem impacts quantitatively. However, invertebrates can be especially sensitive to environmental conditions and predation as many are sessile. There needs to be a way to incorporate ecosystem impacts on these species indirectly so that even with lack of data, qualitative information (i.e. expert knowledge) could be used to test the robustness of these fisheries under a wide range of possible scenarios. Closed-loop simulation through openMSE allowed us to incorporate ecosystem impacts by simulating a range of potential ecosystem impacts identified through expert knowledge. This simulation framework provides an approach to understand how robust management options are to these impacts, when directly including ecosystem impacts in a stock assessment model is not an option. It can also help triage what ecosystem impacts your stock is likely to be most vulnerable to and where to focus your resources. This work shows that closed-loop simulation can be a viable option to account for ecosystem impacts for invertebrates and other species when these impacts cannot be modelled directly due to data and/or model limitations. 

## Using an index of biological condition to inform time varying natural mortality of Atlantic Cod in 3Ps. (Divya Varkey, NL) 

Fisheries stock assessments traditionally assume that natural mortality (M) is constant across all ages and years and typically set at a value of 0.2. For the southern Newfoundland stock of cod (3Ps cod), prior assessments indicated an increase in total mortality, necessitating models that incorporate time-varying M. We developed models with time-invariant and time-varying M. A time-invariant base natural mortality level of M=0.3 was chosen because estimates from neighboring cod stocks and tagging data suggested M levels higher than the traditional 0.2, and this value facilitates similar base levels across both time-invariant and time-varying modeling approaches. The methodology for time-varying M hypothesizes that M is a function of fish condition, specifically hypothesizing that low 'energetic condition' following the spring spawning season increases the fish's vulnerability to environmental stressors. A condition-based index of M (Mc) was developed using fish length and weight data from DFO RV surveys (starting 1978) and sentinel surveys (starting 1995). This model accounts for seasonal variations in condition (low in spring, high in late summer). For applying in the fish stock assessment model, the Mc index was normalized; this normalization involves scaling the Mc  index using the mean and standard deviation calculated over a reference period (1978 to 2012). This scaling allows the covariate to be treated as an anomaly, resulting in M estimates above or below the baseline M=0.3. Parameters mpar estimated within the assessment quantify the influence of the covariate on the trend on M: an estimate close to zero suggests little influence. M positively tracks the normalized Mc covariate trend when mpar is positive; a higher mpar value indicates tighter alignment with that trend. The mpar parameter was estimated separately for two age groups (immature and mature) to enable different responses to changes in fish condition for the two age-groups. 

## Evaluating the impact of time-varying parameters under varying quantities of age data (Mackenzie Mazur, PAC) 

Ecosystem-driven changes are increasingly affecting fish stock dynamics, yet integrating these effects into single-species stock assessment models remains challenging, especially when data are limited. This study uses closed-loop simulations to evaluate how missing age data, combined with different age-structured model assumptions (constant parameters vs. random effects) affect the performance of stock assessments for Petrale Sole in British Columbia under time-varying life histories. Results highlight the importance of age data in capturing ecosystem impacts and informing management advice under changing environmental conditions. Future work will extend this framework to explore the performance of index-based assessment methods under ecosystem-drive changes. 

## Developing CSAS advice for Reference Points in Non-Stationary Conditions under the Fish Stocks Provisions and the Precautionary Approach (Catarina Wor [PAC], Divya Varkey [NL] and Carrie Holt [PAC]) 

Reference points are a key component for the implementation of DFO’s “A fishery decision-making framework incorporating the precautionary approach” (i.e. the PA Policy) which serve as basis for interpreting the Fish Stocks provisions (FSPs) under the revised Fisheries Act. Given the increased impacts of changing conditions on the dynamics of exploited marine resources, Strategic Policy has requested national science advice on a transparent framework for evaluating whether  changing environmental or ecosystem conditions indicate that existing PA reference points may no longer be appropriate.​ The objective of this science advice process is to produce two working papers with the first providing the scientific framework  that contains guidance on developing reference points under non-stationary conditions, including evaluating evidence, assessing risks of different management options, and the conditions  when reference points should be changed, and the second working paper being a compilation of tools and example scenarios of evaluation of reference points under non-stationary conditions within the Canadian context. Any research documents or Science advice arising from this process can be added to the growing inventory of tools and resources available to support DFO’s implementation of an ecosystem approach to fisheries management. 

## Keynote #1: Recent progress towards EBFM in Europe – and some stumbling blocks. Daniel Howell, Institute of Marine Research, Norway 

This talk will give a brief overview of some recent progress towards a better implementation of EBFM in Europe. This will not attempt to be a comprehensive review, but rather focus on topics which have seen recent intensive research focus, covering both ecosystem realism in assessments and single species advice and progress towards better advice on ecosystem management. In particular, there has been a focus on multisectoral conflicts. Driven by EU policy this has especially focussed on better modelling and advice of closed areas (both MPAs and wind farm areas) to better account for the displacement of fishing activity. The talk will also highlight several cases where a lack of political will to agree on choices between conflicting priorities has made progress more difficult. Overall, the science to give better and more relevant ecosystem advice is improving, while challenges remain on translating that into actual ecosystem management. 

## Keynote #2: Myth, mechanism, and misattribution in Ecosystem-Based Fisheries Management. Matt Robertson, Marine Institute, Memorial University of Newfoundland  

Stock assessment models traditionally assumed predictable relationships between fisheries harvest and fish population dynamics. However, fish population dynamics are affected by a variety of ecosystem processes that often invalidate this assumption. Although a variety of approaches now exist to incorporate ecological variation, determining the appropriate level of complexity remains difficult. Here, I will draw on three recent studies to highlight lessons that may be useful for stock assessment scientists hoping to incorporate ecosystem considerations into their models. First, using a simulation study, I will describe how historical assumptions used when modeling environment-recruitment relationships may have biased our perception about the value of these relationships. Second, I will review recent evidence that starvation mortality may represent an overlooked component of natural mortality. Third, I will detail a modeling framework for assessing models across a range of complexity to identify the most likely population and ecosystem processes that affect population dynamics. Together, these examples underscore three principles for ecosystem-informed assessments: 1) modeled truisms about ecology are only true in the context of model assumptions, 2) developing ecosystem-based predictions will require constant re-assessments about which model assumptions are reasonable, and 3) iteratively examining models across a range of model assumptions may provide a useful framework for improving understanding and ensuring that decisions are evidence-based. 

## Keynote #3: Environmental Information in Stock Assessments of New England Groundfish. Steve Cadrin, University of Massachusetts, Dartmouth  

Stock assessment and management of New England groundfish fisheries have been challenged by climate change. As the region rapidly warms, many groundfish stocks fail to rebuild despite precautionary catch limits, and their stock assessments have exhibited diagnostic problems such as severe retrospective patterns. In response to this problem, a collaboration of regional scientists developed an approach to consider environmental information in New England stock assessments. The process involves 1) reviewing information on ecological interactions for each assessed species, 2) testing relationships between environmental indices and population processes (e.g., distribution, recruitment, growth, maturity), and 3) developing stock assessment models with environmental covariates to determine stock status and management advice. The process was applied to relatively data-rich research track assessments American plaice, Atlantic cod, yellowtail flounder, and winter flounder, with iterative progress toward operational application. The most recent yellowtail flounder stock assessments that were accepted for management advice include environmental covariates but demonstrate challenges with catch projections and management reference points. These case studies demonstrate an effective approach to including ecosystem information in stock assessments as well as the need for iterative advancement as the approach is applied more broadly. 

## salmonMSE: a decision-support tool for Pacific salmon accounting for within-population life-history diversity and environmental drivers (Carrie Holt, PAC)  

Risk-based decision support tools are needed for Pacific salmon to inform sustainable management. Like other taxonomic groups, management is expected to account for the biology of the fish and environmental conditions affecting the stock. However, Pacific salmon are unique in several ways resulting in the need for distinct tools. Pacific salmon have high biological diversity, are impacted by environmental conditions in freshwater and marine environments, and their management spans fishery harvest, hatchery enhancement and habitat restoration. salmonMSE is a stochastic, closed-loop simulation tool based on ‘management strategy evaluation’ (MSE) using a life cycle-based model that can incorporate biological realism of salmon populations with harvest, hatchery and habitat management levers. While salmonMSE is a generic tool, it is adaptable to different salmon species, with varying biological characteristics, data availabilities and management contexts. Here, we present a case study on Chinook salmon on the West Coast of Vancouver Island that is exposed to mixed-stock fisheries, and subject to hatchery enhancement and habitat restoration. The model is conditioned on available spawner time-series, hatchery releases, and (coded wire) tagging data, and projections are expanded to include hypotheses about life-history diversity within the populations (early and late maturing fish with different survival rates), and environmental drivers of freshwater survival. In this way management scenarios can be evaluated under various assumptions about the biology of the fish and ecosystem drivers even when data are insufficient to include in the assessment and conditioning model. Future additions to salmonMSE will include a conditioning model that attempts to take the influence of ecosystem conditions on marine mortality (e.g., predators, SST) directly into account. 

## Time-varying models for Pacific salmon: estimation, model selection and closed-loop simulations (Catarina Wor, PAC)  

Time-varying population dynamics in fish populations are becoming increasingly common due to effects of climate change, habitat degradation and other anthropogenic factors. This is particularly true for Pacific salmon stocks which are susceptible changes in both marine and freshwater environments. In contrast, fisheries reference points are often estimated under the assumption of stationary dynamics, which can lead to science advice that is not sufficiently precautionary or that limits fisheries unnecessarily. However, accurately estimating time-varying dynamics is often difficult, and including time-varying parameters in harvest control rules may not necessarily lead to improved management outcomes. We used a closed-loop simulation approach to evaluate the performance of management strategies given different scenarios of changing spawner-recruit dynamics in Pacific salmon, including changes to the productivity and capacity parameters. We considered harvest control rules based on fixed, stationary and time-varying abundance and removal rate reference points assessed at different frequencies. Our results indicate that there are interactions between the shape of the harvest control rules and the use of different combinations of stationary and time-varying for both abundance and removal reference points. This suggest that the choice of reference points should not be done in isolation but within the context of the harvest control rule and other management strategies being considered.   

## Incorporation of hydroclimate and exploitation impacts into monitoring, assessment and management of anadromous Dolly Varden population productivity (Xinhua Zhu and Colin Gallagher, ARC)  

A warming climate in the western Canadian Arctic has impacted seasonal discharge of rivers, which provides important habitat for anadromous salmonids. Strong seasonal variations in weather and hydroclimate conditions have been identified as an environmental driver impacting the timing of seasonal migrations of anadromous fish populations.  

Subsistence fisheries in the western Canadian Arctic rely on stocks of anadromous Arctic Char and Dolly Varden to ensure food security and transmit cultural practices. In response to a decline in the abundance of anadromous Dolly Varden in the Rat River, Northwest Territories, an annual fisheries-dependent community-based monitoring program was initiated in 1995. Experienced Gwich’in harvesters implemented this program to collect fisheries data, including catch-effort and biological information during the upstream migration (late-July to mid-September). Additionally, several qualitative categorical variables pertaining to water level, debris, and water clarity were recorded to track the temporal changes in the environmental conditions and link them to the relative abundance index of migrating Dolly Varden. The assessment of temporal changes in weather and hydrometric indicators may contribute to our better understanding of impacts on the seasonal migration timing and population dynamics, although the qualitative environmental information is difficult to directly apply to quantitative stock assessment.  

To incorporate the ecosystem indicators recorded by the harvesters into a stock assessment, our EAFM approach was to i) establish scenario-based causal models linking catch-per-unit-effort of Dolly Varden with the qualitative and quantitative ecosystem indicators, ii) estimate population dynamics parameters using a Bayesian state-space surplus production model, and iii) develop fisheries reference points delineating the historical and current stock status of the population among scenarios. The modelling indicated that the stock is currently in a healthy state. The outcomes will promote an integrated assessment plan for the stock that incorporates environmental considerations. 

## Modelled reconstructions of marine environmental and ecosystem variables: trends, causal inference, and recent applications in the Pacific Region (Greig Oldford, PAC)  

Reconstructions of unobserved environmental and ecosystem variables are increasingly available. Many of these reconstructions include quantification of uncertainty and have been evaluated against the available observational data. An emerging challenge relates to a surplus of potentially relevant time series and covariates. This talk will highlight recent applications of biogeochemical and ecosystem models and causal inference for supporting stock assessments. 

## Drivers of Pacific Hake recruitment -- lessons learned from trying to operationalize the research (Andrew Edwards, PAC)  

Pacific hake (*Merluccius productus*) is a commercially valuable fish species of importance to Canada and the United States. It is assessed and managed bilaterally as a single stock. Published research has determined relevant ecosystem information that appears to influence hake recruitment. Some of the more easily available and updatable information (such as that available in DFO's pacea R package) was amalgamated and presented in the 2025 assesment document, as a first step to developing a reproducible workflow for incorporating some of this information into the model. Lessons learned will be described. The current assessment model does currently include temperature as an environmental predictor of spatiotemporal maturity-at-age, and uses empirical weight-at-age data. These will be briefly described as examples of including ecosystem information in the age-structured model. 

## Exploring environmental effects on fish stock recruitment - tools to bolster EAFM and contributions toward CSAS reports (Travis Tai, PAC)  

Ecosystem variables can provide valuable insight into biological drivers of fish stock recruitment, yet are not always explicitly included in stock assessments and fisheries management. Here we present methods and resources that streamline the process of integrating environmental analyses in stock assessments. The analyses are introductory and exploratory, assessing each variable separately in a univariate model. It uses readily available ecosystem data from the R package `pacea`, facilitating its use across different species and stock assessments. While this approach is basic, it acts as a foundation for further investigation into specific environmental variables and more complex modelling approaches. 

## The use of ecosystem variables in 2J3KL Capelin assessments (Aaron Adamack, NL)  

Capelin is a forage fish species with a circumpolar distribution. They play key roles in multiple sub-Arctic food webs and are considered to be a keystone species in North Atlantic Fisheries Organization Divisions 2J3KL. The current year’s capelin biomass index in 2J3KL is predicted using a modeling suite that is based upon two theories of how capelin biomass is regulated: cohort strength and adult mortality. Two cohort strength models use larval capelin density alone or in combination with zooplankton density to predict the capelin biomass index while two adult morality models use the timing of sea ice retreat alone or in combination with fall condition of age-1 and -2 capelin. A third set of models combine the different cohort strength and adult mortality models in various combinations resulting in an overall total of 10 forecast models. The environmental variables used in these models reflect the environmental drivers affecting capelin biomass where the cohort strength models are focused around environmental drivers of capelin reproductive success while the adult mortality are focused of drivers that address the ability of capelin to survive harsh winters in the NW Atlantic. The best fitting model uses all 4 variables and has a Bayesian R2 = 0.62. 

## Linking Prey and Predators: How Capelin Informs the Northern Cod Stock Assessment (Paul Regular, NL)  

Northern cod (*Gadus morhua*) off Newfoundland and Labrador collapsed in the early 1990s following decades of heavy fishing and coinciding with major ecosystem change in the Northwest Atlantic. Since then, the stock’s slow and uneven recovery has continued to draw attention to the ecosystem processes shaping its productivity. Among the potential drivers – including fishing, temperature, predation, and prey availability – capelin (*Mallotus villosus*) has emerged as a key factor influencing cod condition, recruitment, and survival. 

\newpage

# Annexe `r new_appendix()`. Breakout Group topics identified prior to the workshop {#app:third-appendix}

Prior to the workshop, participants were ask to provide ideas of topics for break-out group discussions and work. While the intention was to identify additional topics during the workshop the following initial set was retained: 

## When M Isn’t Constant: Ecosystem-Driven Mortality and Its Consequences for Management Advice.  Host: Paul Regular  

Natural mortality is dynamic, but we often lack the data or understanding of stock dynamics needed to estimate changes through time. Introducing ecosystem drivers such as prey availability introduces time-varying natural mortality into stock assessments, adding realism but also complexity. Using Northern cod as an example, this breakout will examine how changes in M linked to ecosystem variability, such as shifts in capelin abundance, affect reference points, rebuilding trajectories and perceptions of risk. Discussion will focus on the dual challenge of capturing ecological realism while maintaining clarity and confidence in management advice, and on effective ways to communicate these dynamics to decision-makers and stakeholders.  

## Incorporating qualitative ecosystem information into stock assessment models. Host: Mackenzie Mazur  

Although the literature has primarily focused on the integration of quantitative ecosystem information into single-species stock assessment, incorporating qualitative ecosystem information (i.e. expert knowledge, traditional knowledge) remains a significant challenge. However, for many stocks, especially those that are data-limited, qualitative information may be the only available source of information on ecosystem impacts. This breakout group will explore approaches for incorporating qualitative ecosystem information into assessment models, which could include testing or simulating a range of ecosystem scenarios informed by qualitative input or using qualitative information to inform priors for key parameters. The goal is to brainstorm novel and transparent approaches for incorporating ecosystem impacts in stock assessments when quantitative ecosystem data are limited.  

## Approaches for considering the spatial and demographic scale of environmental drivers when including those drivers in assessments. Host: Matt Robertson.   

The incorporation of ecosystem information into single-species stock assessment models has often focused on the inclusion of a time-series of some environmental covariate to explain temporal variation in some demographic process. However, we know that environmental effects often differ in strength, magnitude, and direction at relatively fine spatial scales and across an animal’s ontogeny. The goal of this breakout group will be to discuss approaches for integrating analyses of environmental effects across spatial and demographic scales with stock assessments.  

## Use of Simulation testing to evaluate impacts of ecosystem changes on Fisheries management Host: Catarina Wor  

Simulation evaluation of estimation models. Use of closed loop simulations. Cluster computing is now available via DFO GPHPC. How can we make it more accessible?

<!-- At the end of your appendices add: -->
`r if(knitr:::is_latex_output()) '% end csasdown appendix'`
